export enum FilterClassEnum {
  None = '',
  Yellow = 'filterYellow',
  LightYellow = 'filterLightYellow',
  Orange = 'filterOrange',
  LightOrange = 'filterLightOrange',
  OffBlack = 'filterOffBlack',
  DarkBlue = 'filterDarkBlue',
  Blue = 'filterBlue',
  LightBlue = 'filterLightBlue',
  Gray = 'filterGray',
  LightGray = 'filterLightGray',
  Teal = 'filterTeal',
  White = 'filterWhite',
  Black = 'filterBlack',
  Red = 'filterRed',
  LightRed = 'filterLightRed',
}
