export enum SkillTitle {
  Tadpole = 'Tadpole Skills',
  Starfish = 'Starfish Skills',
  Goldfish = 'Goldfish Skills',
  Jellyfish = 'Jellyfish Skills',
  Seahorse = 'Seahorse Skills',
  Dolphin = 'Dolphin Skills',
  Seal = 'Seal Skills',
  AdultBeginner = 'Adult Beginner',
  AdultIntermediate = 'Adult Intermediate',
  AdultAdvanced = 'Adult Advanced',
  SpecializedTraining = 'Specialized Training',
  BabyTadpole = 'Baby Tadpole Skills',
  BabyStarfish = 'Baby Starfish Skills',
  BabyGoldfish = 'Baby Goldfish Skills',
  BabyJellyfish = 'Baby Jellyfish Skills',
}