-- CreateTable
CREATE TABLE `customer_registration_record_history` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `record_id` BIGINT NULL,
    `data` TEXT NULL,

    INDEX `record_id`(`record_id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- CreateTable
CREATE TABLE `customer_registration_records` (
    `id` BIGINT NOT NULL AUTO_INCREMENT,
    `orderId` BIGINT NULL,
    `isRegistrationComplete` BOOLEAN NULL,
    `metroArea` VARCHAR(200) NULL,
    `additionalPayForSI` DECIMAL(10, 2) NULL,
    `doWeHaveSIWithPool` BOOLEAN NULL,
    `canWeServe` BOOLEAN NULL,
    `canWeServeText` VARCHAR(200) NULL,
    `firstName` VARCHAR(200) NULL,
    `lastName` VARCHAR(200) NULL,
    `email` VARCHAR(200) NULL,
    `phone` VARCHAR(200) NULL,
    `zip` VARCHAR(5) NULL,
    `customerHasAccessToPool` BOOLEAN NULL,
    `registrationDate` VARCHAR(200) NULL,
    `premiumAreaFee` DECIMAL(10, 2) NULL,
    `studentsCount` INTEGER NULL,
    `questionsOfInformationWeShouldNowAboutTheStudents` TEXT NULL,
    `isCustomerAParentGuardianOfAll` BOOLEAN NULL,
    `additionalParentGuardiansCount` INTEGER NULL,
    `hasStudentsAboveThreeYearsOld` BOOLEAN NULL,
    `lessonType` VARCHAR(200) NULL,
    `lessonTime` INTEGER NULL,
    `packageSize` INTEGER NULL,
    `basePay` DECIMAL(10, 2) NULL,
    `totalBasePay` DECIMAL(10, 2) NULL,
    `lessonCostBeforeDiscount` DECIMAL(10, 2) NULL,
    `packageDiscount` DECIMAL(10, 2) NULL,
    `lessonFrequency` INTEGER NULL,
    `customerWouldLikeToBegin` VARCHAR(200) NULL,
    `preferredLessonBeginDate` VARCHAR(200) NULL,
    `customerAvailableUntil` VARCHAR(200) NULL,
    `additionalSchedulingInformation` TEXT NULL,
    `bookability` VARCHAR(200) NULL,
    `poolAddress` VARCHAR(200) NULL,
    `poolType` VARCHAR(200) NULL,
    `howFarCustomerWillingToDrive` VARCHAR(200) NULL,
    `validatedPromoCode` VARCHAR(200) NULL,
    `eligibleLsg` BOOLEAN NULL,
    `haveCustomerBeenHelpedBy` VARCHAR(200) NULL,
    `lg1Signed` BOOLEAN NULL,
    `lg1SigningDate` VARCHAR(200) NULL,
    `freeLessons` INTEGER NULL,
    `paidLessons` INTEGER NULL,
    `promoDiscount` DECIMAL(10, 2) NULL,
    `orderTotal` DECIMAL(10, 2) NULL,
    `stripeToken` VARCHAR(200) NULL,
    `selectedDays` VARCHAR(200) NULL,
    `selectedWeekdayTimes` VARCHAR(200) NULL,
    `selectedWeekendTimes` VARCHAR(200) NULL,
    `studentName1` VARCHAR(200) NULL,
    `studentAge1` VARCHAR(200) NULL,
    `studentName2` VARCHAR(200) NULL,
    `studentAge2` VARCHAR(200) NULL,
    `studentName3` VARCHAR(200) NULL,
    `studentAge3` VARCHAR(200) NULL,
    `studentName4` VARCHAR(200) NULL,
    `studentAge4` VARCHAR(200) NULL,
    `studentName5` VARCHAR(200) NULL,
    `studentAge5` VARCHAR(200) NULL,
    `studentName6` VARCHAR(200) NULL,
    `studentAge6` VARCHAR(200) NULL,
    `parentGuardianName1` VARCHAR(200) NULL,
    `parentGuardianEmail1` VARCHAR(200) NULL,
    `parentGuardianName2` VARCHAR(200) NULL,
    `parentGuardianEmail2` VARCHAR(200) NULL,
    `parentGuardianName3` VARCHAR(200) NULL,
    `parentGuardianEmail3` VARCHAR(200) NULL,
    `parentGuardianName4` VARCHAR(200) NULL,
    `parentGuardianEmail4` VARCHAR(200) NULL,
    `parentGuardianName5` VARCHAR(200) NULL,
    `parentGuardianEmail5` VARCHAR(200) NULL,
    `parentGuardianName6` VARCHAR(200) NULL,
    `parentGuardianEmail6` VARCHAR(200) NULL,
    `secret` VARCHAR(100) NULL,
    `ip` VARCHAR(50) NULL,
    `ad_call` VARCHAR(3) NULL,
    `referralCreditSpent` BIGINT NULL,
    `referralLessonsSpent` BIGINT NULL,
    `registrationFormType` VARCHAR(10) NULL,
    `deviceCategory` VARCHAR(200) NULL,
    `deviceType` VARCHAR(200) NULL,
    `requestedInstructor` VARCHAR(200) NULL,
    `upsell_from` BIGINT NULL DEFAULT 0,
    `priceMultiplier` DECIMAL(10, 2) NULL,
    `payMultiplier` DECIMAL(10, 2) NULL,
    `termsFullName` VARCHAR(200) NULL,
    `flexibleSchedule` BOOLEAN NULL,

    INDEX `orderId`(`orderId`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- AddForeignKey
ALTER TABLE `customer_registration_record_history` ADD CONSTRAINT `customer_registration_record_history_ibfk_1` FOREIGN KEY (`record_id`) REFERENCES `customer_registration_records`(`id`) ON DELETE RESTRICT ON UPDATE RESTRICT;

